### ISSUE TITLE
Add website link in the footer

### ISSUE THREAD

**Issue by Matic0B** [StratusNetwork/xml#18]

**Comment by stormer1267** [comment]
something like this? 
https://github.com/StratusNetwork/XML-Documentation/pull/19

**Comment by Matic0B** [comment]
Might be better to have something more recognizable overall, like a home icon or something like that.

**Comment by stormer1267** [comment]
Maybe make the stratus logo go to the stratus website (in the navbar)? or you could just make the copyright text a clickable link

**Comment by Matic0B** [comment]
The logo could work
